image: adoptopenjdk:15-jdk-hotspot

tags:
  - java

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

before_script:
  - chmod +x ./gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle



build:
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test:
  stage: test
  script:
    - ./gradlew check

deploy:
  stage: deploy
  script:
    - ./gradlew publish
  rules:
    - changes:
        - gradle.properties

