image: adoptopenjdk:15-jdk-hotspot

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - .gradle/loom-cache

before_script:
  - chmod +x ./gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  tags:
    - java
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test:
  stage: test
  tags:
    - java
  script:
    - ./gradlew check

deploy:
  stage: deploy
  tags:
    - java
  script:
    - ./gradlew publish
  rules:
    - changes:
        - gradle.properties
